// Import Invoice (§2 step 5, Invoicing — Import). Ported from main's
// import_invoices_t + import_invoice_items_t. Import invoices reference multiple
// MCAs via the comma-separated mca_ids column (main's model) rather than a child
// table. Header is a transaction-page; items are managed by the custom grid.
import { pgTable, serial, integer, varchar, date, numeric, text, timestamp, index } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { usersT } from './users';
import { clientMaster } from './clients';

export const importInvoices = pgTable(
  'import_invoices_t',
  {
    id: serial('id').primaryKey(),
    clientId: integer('client_id').references(() => clientMaster.id),
    licenseId: integer('license_id'),
    licenseIds: varchar('license_ids', { length: 255 }),
    mcaId: integer('mca_id'),
    mcaIds: varchar('mca_ids', { length: 500 }),
    kindId: integer('kind_id'),
    goodsTypeId: integer('goods_type_id'),
    transportModeId: integer('transport_mode_id'),
    invoiceRef: varchar('invoice_ref', { length: 100 }),
    tallyRef: varchar('tally_ref', { length: 100 }),
    dgiAmount: numeric('dgi_amount', { precision: 15, scale: 2 }).default('0'),
    normalizedBy: integer('normalized_by'),
    paymentMethod: varchar('payment_method', { length: 30 }).default('CREDIT'),
    fobCurrencyId: integer('fob_currency_id'),
    fobUsd: numeric('fob_usd', { precision: 15, scale: 2 }).default('0'),
    fretCurrencyId: integer('fret_currency_id'),
    fretUsd: numeric('fret_usd', { precision: 15, scale: 2 }).default('0'),
    assuranceCurrencyId: integer('assurance_currency_id'),
    assuranceUsd: numeric('assurance_usd', { precision: 15, scale: 2 }).default('0'),
    autresChargesCurrencyId: integer('autres_charges_currency_id'),
    autresChargesUsd: numeric('autres_charges_usd', { precision: 15, scale: 2 }).default('0'),
    rateCdfInv: numeric('rate_cdf_inv', { precision: 15, scale: 6 }).default('2500'),
    rateCdfUsdBcc: numeric('rate_cdf_usd_bcc', { precision: 15, scale: 6 }).default('2500'),
    rateCdfClient34: numeric('rate_cdf_client34', { precision: 15, scale: 6 }),
    cifUsd: numeric('cif_usd', { precision: 15, scale: 2 }).default('0'),
    cifCdf: numeric('cif_cdf', { precision: 18, scale: 2 }).default('0'),
    totalDutyCdf: numeric('total_duty_cdf', { precision: 18, scale: 2 }).default('0'),
    poidsKg: numeric('poids_kg', { precision: 15, scale: 2 }).default('0'),
    m3: numeric('m3', { precision: 15, scale: 2 }),
    tariffCodeClient: varchar('tariff_code_client', { length: 100 }),
    horse: varchar('horse', { length: 100 }),
    trailer1: varchar('trailer_1', { length: 100 }),
    trailer2: varchar('trailer_2', { length: 100 }),
    container: varchar('container', { length: 100 }),
    wagon: varchar('wagon', { length: 100 }),
    airwayBill: varchar('airway_bill', { length: 100 }),
    airwayBillWeight: numeric('airway_bill_weight', { precision: 15, scale: 2 }),
    facturePfiNo: varchar('facture_pfi_no', { length: 100 }),
    poRef: varchar('po_ref', { length: 100 }),
    bivacInspection: varchar('bivac_inspection', { length: 100 }),
    produit: varchar('produit', { length: 255 }),
    exonerationCode: varchar('exoneration_code', { length: 100 }),
    declarationNo: varchar('declaration_no', { length: 100 }),
    declarationDate: date('declaration_date'),
    liquidationNo: varchar('liquidation_no', { length: 100 }),
    liquidationDate: date('liquidation_date'),
    quittanceNo: varchar('quittance_no', { length: 100 }),
    quittanceDate: date('quittance_date'),
    dispatchDeliverDate: date('dispatch_deliver_date'),
    bankId: integer('bank_id'),
    quotationId: integer('quotation_id'),
    quotationSubTotal: numeric('quotation_sub_total', { precision: 15, scale: 2 }),
    quotationVatAmount: numeric('quotation_vat_amount', { precision: 15, scale: 2 }),
    quotationTotalAmount: numeric('quotation_total_amount', { precision: 15, scale: 2 }),
    calculatedSubTotal: numeric('calculated_sub_total', { precision: 15, scale: 2 }).default('0'),
    calculatedVatAmount: numeric('calculated_vat_amount', { precision: 15, scale: 2 }).default('0'),
    calculatedTotalAmount: numeric('calculated_total_amount', { precision: 15, scale: 2 }).default('0'),
    calculatedTotalCdf: numeric('calculated_total_cdf', { precision: 18, scale: 2 }).default('0'),
    itemsManuallyEdited: integer('items_manually_edited').default(0),
    firstCategotyEdited: varchar('first_categoty_edited', { length: 1 }).default('H'),
    invoiceTemplate: varchar('invoice_template', { length: 5 }),
    arsp: varchar('arsp', { length: 20 }).default('Disabled'),
    hiddenCategories: text('hidden_categories').default('[]'),
    isDebited: integer('is_debited').default(0),
    isInvoiced: integer('is_invoiced').default(0),
    validated: integer('validated').notNull().default(0),
    display: varchar('display', { length: 1 }).notNull().default('Y'),
    createdBy: integer('created_by').references(() => usersT.id, { onDelete: 'set null' }),
    updatedBy: integer('updated_by').references(() => usersT.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: false }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: false }).defaultNow().notNull(),
  },
  (t) => ({
    clientIdx: index('idx_import_invoices_t_client').on(t.clientId),
    validatedIdx: index('idx_import_invoices_t_validated').on(t.validated),
    createdByIdx: index('idx_import_invoices_t_created_by').on(t.createdBy),
  }),
);

export const importInvoiceItems = pgTable(
  'import_invoice_items_t',
  {
    id: serial('id').primaryKey(),
    invoiceId: integer('invoice_id').notNull(),
    quotationItemId: integer('quotation_item_id'),
    categoryId: integer('category_id'),
    categoryName: varchar('category_name', { length: 255 }),
    categoryHeader: varchar('category_header', { length: 255 }),
    itemId: integer('item_id'),
    itemName: varchar('item_name', { length: 500 }),
    itemDescription: text('item_description'),
    unitId: integer('unit_id'),
    unitName: varchar('unit_name', { length: 100 }),
    unitText: varchar('unit_text', { length: 100 }),
    quantity: numeric('quantity', { precision: 15, scale: 3 }).default('1'),
    tauxUsd: numeric('taux_usd', { precision: 15, scale: 4 }).default('0'),
    costUsd: numeric('cost_usd', { precision: 15, scale: 4 }).default('0'),
    currencyId: integer('currency_id'),
    currencyShortName: varchar('currency_short_name', { length: 20 }),
    hasTva: integer('has_tva').default(0),
    tvaUsd: numeric('tva_usd', { precision: 15, scale: 2 }).default('0'),
    subtotalUsd: numeric('subtotal_usd', { precision: 15, scale: 2 }).default('0'),
    totalUsd: numeric('total_usd', { precision: 15, scale: 2 }).default('0'),
    cifSplit: numeric('cif_split', { precision: 18, scale: 2 }).default('0'),
    percentage: numeric('percentage', { precision: 12, scale: 4 }).default('0'),
    rateCdf: numeric('rate_cdf', { precision: 18, scale: 2 }).default('0'),
    vatCdf: numeric('vat_cdf', { precision: 18, scale: 2 }).default('0'),
    totalCdf: numeric('total_cdf', { precision: 18, scale: 2 }).default('0'),
    sortOrder: integer('sort_order').default(0),
    display: varchar('display', { length: 1 }).notNull().default('Y'),
    createdBy: integer('created_by').references(() => usersT.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: false }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: false }).defaultNow().notNull(),
  },
  (t) => ({ invIdx: index('idx_iii_invoice').on(t.invoiceId) }),
);

export const importInvoicesRelations = relations(importInvoices, ({ one, many }) => ({
  client: one(clientMaster, { fields: [importInvoices.clientId], references: [clientMaster.id] }),
  items: many(importInvoiceItems),
}));

export type ImportInvoiceRow = typeof importInvoices.$inferSelect;
export type ImportInvoiceInsert = typeof importInvoices.$inferInsert;
