INSERT INTO "truck_status_master_t" ("id", "truck_status", "display", "created_by", "updated_by", "created_at", "updated_at") VALUES
	(1, 'AMENDMENT FOR TRANSPORT DOCUMENTS', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(2, 'CUSTOMS MANIFEST TO BE GENERATED', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(3, 'DOCUMENTS HANDED OVER TO THE TRANSPORTER/ RUNNER', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(4, 'DOCUMENTS TO BE COLLECTED BY THE RUNNER', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(5, 'ENTRY CARD TO BE RECEIVED FROM THE TRANSPORTER/ RUNNER', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(6, 'ERROR IN THE DECLARATION / DECLARATION TO BE AMENDED', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(7, 'EXPECTED TO ARRIVE', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(8, 'IM4/T1 TO BE GENERATED', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(9, 'PARKING FEES TO BE PAID BY THE TRANSPORTER', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(10, 'QUITTANCE TO BE UPDATED IN THE SYSTEM', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(11, 'RESTRICTED IMPORTATION - OCC TO BE AUTHORIZED', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(12, 'SEGUCE TO BE PAID', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(13, 'TRUCK TO BE LOCATED', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(14, 'TRUCK AT K''LESA ZAMBIAN SIDE', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(15, 'WAITING FOR THE LIQUIDATION PAYMENT', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(16, 'FICHE DE CALCUL TO BE VALIDATED', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(17, 'UNDER PROCESS', 'Y', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--> statement-breakpoint
SELECT setval(pg_get_serial_sequence('truck_status_master_t', 'id'), (SELECT MAX(id) FROM "truck_status_master_t"));
