import type { ExportBody } from '@/schemas/exports';

// Map the snake_case API body to camelCase Drizzle insert/update.
// Mirrors the pattern in src/lib/imports/serialize.ts — the boundary
// keys and DB column names can drift independently of each other.

export function bodyToInsert(body: ExportBody): Record<string, unknown> {
  return {
    clientId: body.client_id,
    licenseId: body.license_id,
    kind: body.kind_id,
    typeOfGoods: body.type_of_goods_id,
    transportMode: body.transport_mode_id,
    mcaRef: body.mca_ref,
    currency: body.currency_id,
    buyer: body.buyer,
    regime: body.regime_id,
    typesOfClearance: body.types_of_clearance_id,
    invoice: body.invoice,
    poRef: body.po_ref,
    bpNo: body.bp_no,
    weight: body.weight,
    fob: body.fob,
    numberOfBags: body.number_of_bags,
    lotNumber: body.lot_number,
    horse: body.horse,
    trailer1: body.trailer_1,
    trailer2: body.trailer_2,
    feetContainer: body.feet_container_id,
    wagonRef: body.wagon_ref,
    container: body.container,
    transporter: body.transporter,
    siteOfLoadingId: body.site_of_loading_id,
    destination: body.destination,
    exitPointId: body.exit_point_id,
    dgdaSealNo: body.dgda_seal_no,
    numberOfSeals: body.number_of_seals,
    ceecAmount: body.ceec_amount,
    cgeaAmount: body.cgea_amount,
    occAmount: body.occ_amount,
    lmcAmount: body.lmc_amount,
    ogefremAmount: body.ogefrem_amount,
    loadingDate: body.loading_date,
    pvDate: body.pv_date,
    bpDate: body.bp_date,
    demandeAttestationDate: body.demande_attestation_date,
    assayDate: body.assay_date,
    archiveReference: body.archive_reference,
    ceecInDate: body.ceec_in_date,
    ceecOutDate: body.ceec_out_date,
    minDivInDate: body.min_div_in_date,
    minDivOutDate: body.min_div_out_date,
    cgeaDocRef: body.cgea_doc_ref,
    seguesRcvRef: body.segues_rcv_ref,
    seguesPaymentDate: body.segues_payment_date,
    documentStatus: body.document_status_id,
    customsClearingCode: body.customs_clearing_code,
    dgdaInDate: body.dgda_in_date,
    declarationReference: body.declaration_reference,
    liquidationReference: body.liquidation_reference,
    liquidationDate: body.liquidation_date,
    liquidationPaidBy: body.liquidation_paid_by,
    liquidationAmount: body.liquidation_amount,
    quittanceReference: body.quittance_reference,
    quittanceDate: body.quittance_date,
    dgdaOutDate: body.dgda_out_date,
    govDocsInDate: body.gov_docs_in_date,
    govDocsOutDate: body.gov_docs_out_date,
    dispatchDeliverDate: body.dispatch_deliver_date,
    kanyakaArrivalDate: body.kanyaka_arrival_date,
    kanyakaDepartureDate: body.kanyaka_departure_date,
    borderArrivalDate: body.border_arrival_date,
    exitDrcDate: body.exit_drc_date,
    endOfFormalitiesDate: body.end_of_formalities_date,
    truckStatus: body.truck_status_id,
    lmcId: body.lmc_id,
    ogefremInvRef: body.ogefrem_inv_ref,
    loadingToDispatchDate: body.loading_to_dispatch_date,
    lmcDate: body.lmc_date,
    ogefremDate: body.ogefrem_date,
    auditedDate: body.audited_date,
    archivedDate: body.archived_date,
    clearingStatus: body.clearing_status_id,
    remarks: body.remarks,
  };
}
