import type { ImportBody } from '@/schemas/imports';

// Map the snake_case API body to the camelCase Drizzle insert/update
// object. Done explicitly (rather than a transform on the Zod schema)
// so the boundary keys and the DB column names can drift independently
// — e.g. a future renaming of `mcaRef` doesn't break the API contract.

export function bodyToInsert(body: ImportBody): Record<string, unknown> {
  return {
    clientId: body.client_id,
    licenseId: body.license_id,
    partialId: body.partial_id,
    kindId: body.kind_id,
    typeOfGoodsId: body.type_of_goods_id,
    transportModeId: body.transport_mode_id,
    mcaRef: body.mca_ref,
    currencyId: body.currency_id,
    licenseInvoiceNumber: body.license_invoice_number,
    supplier: body.supplier,
    regimeId: body.regime_id,
    typesOfClearanceId: body.types_of_clearance_id,
    declarationOfficeId: body.declaration_office_id,
    preAlertDate: body.pre_alert_date,
    invoice: body.invoice,
    commodityId: body.commodity_id,
    poRef: body.po_ref,
    fret: body.fret,
    fretCurrencyId: body.fret_currency_id,
    otherCharges: body.other_charges,
    otherChargesCurrencyId: body.other_charges_currency_id,
    weight: body.weight,
    remWeight: body.rem_weight,
    m3: body.m3,
    cessionDate: body.cession_date,
    fob: body.fob,
    rFob: body.r_fob,
    rFobCurrencyId: body.r_fob_currency_id,
    fobCurrencyId: body.fob_currency_id,
    insuranceDate: body.insurance_date,
    insuranceAmount: body.insurance_amount,
    insuranceAmountCurrencyId: body.insurance_amount_currency_id,
    insuranceReference: body.insurance_reference,
    crfReference: body.crf_reference,
    crfReceivedDate: body.crf_received_date,
    clearingBasedOn: body.clearing_based_on,
    adDate: body.ad_date,
    inspectionReports: body.inspection_reports,
    archiveReference: body.archive_reference,
    auditedDate: body.audited_date,
    archivedDate: body.archived_date,
    roadManif: body.road_manif,
    airwayBill: body.airway_bill,
    container: body.container,
    entryPointId: body.entry_point_id,
    wagon: body.wagon,
    airwayBillWeight: body.airway_bill_weight,
    horse: body.horse,
    trailer1: body.trailer_1,
    trailer2: body.trailer_2,
    dgdaInDate: body.dgda_in_date,
    declarationReference: body.declaration_reference,
    seguesRcvRef: body.segues_rcv_ref,
    seguesPaymentDate: body.segues_payment_date,
    customsManifestNumber: body.customs_manifest_number,
    customsManifestDate: body.customs_manifest_date,
    customsClearanceCode: body.customs_clearance_code,
    dgdaOutDate: body.dgda_out_date,
    documentStatusId: body.document_status_id,
    declarationValidity: body.declaration_validity,
    t1Number: body.t1_number,
    t1Date: body.t1_date,
    liquidationReference: body.liquidation_reference,
    liquidationDate: body.liquidation_date,
    liquidationPaidBy: body.liquidation_paid_by,
    liquidationAmount: body.liquidation_amount,
    quittanceReference: body.quittance_reference,
    quittanceDate: body.quittance_date,
    airportArrivalDate: body.airport_arrival_date,
    dispatchFromAirport: body.dispatch_from_airport,
    operatingCompany: body.operating_company,
    operatingDays: body.operating_days,
    operatingAmount: body.operating_amount,
    arrivalDateZambia: body.arrival_date_zambia,
    dispatchFromZambia: body.dispatch_from_zambia,
    drcEntryDate: body.drc_entry_date,
    borderWarehouseArrivalDate: body.border_warehouse_arrival_date,
    dispatchFromBorder: body.dispatch_from_border,
    kanyakaArrivalDate: body.kanyaka_arrival_date,
    kanyakaDispatchDate: body.kanyaka_dispatch_date,
    warehouseArrivalDate: body.warehouse_arrival_date,
    warehouseDepartureDate: body.warehouse_departure_date,
    dispatchDeliverDate: body.dispatch_deliver_date,
    ibsCouponReference: body.ibs_coupon_reference,
    borderWarehouseId: body.border_warehouse_id,
    entryCoupon: body.entry_coupon,
    bondedWarehouseId: body.bonded_warehouse_id,
    truckStatus: body.truck_status,
    clearingStatusId: body.clearing_status_id,
    invExportDisabled: body.inv_export_disabled,
    invExportDisabledRemark: body.inv_export_disabled_remark,
    remarks: body.remarks,
  };
}
